version: '3'

services:
  mysql:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
      - "33060:33060"
    container_name: mysql-container-compose
     
  nexus:
    image: sonatype/nexus3
    restart: on-failure
    environment:
      - NEXUS_USERNAME=admin
      - NEXUS_PASSWORD=nexus
    volumes:
      - nexus-data:/nexus-data
    ports:
      - "8081:8081"
    container_name: nexus-compose
    
  sonarqube:
    image: sonarqube
    restart: on-failure
    ports:
    - "9000:9000"
    - "9092:9092"
    volumes:
     - SonarQube_data:/opt/SonarQube/data
     - SonarQube_extensions:/opt/SonarQube/extensions
     - SonarQube_logs:/opt/SonarQube/logs

volumes:
  nexus-data:
  SonarQube_data:
  SonarQube_extensions:
  SonarQube_logs:
